"""
Django settings for vagali_project project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!+=&bi60tm%%a@dwv-n#5$#l+1bgfftv3-vljfytna$vi96fe7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'corsheaders',

    'accounts',
    'rest_framework',
    'django_filters',
    'app_servicos',

    'djoser',
    'rest_framework.authtoken',


]

# 2. Configure o Custom User (IMPORTANTE!)
AUTH_USER_MODEL = 'accounts.User'


# 3. Adicione o redirecionamento de login/logout (ajustaremos as rotas depois)
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# 🚨 4. CRÍTICO: Configuração do Backend de Autenticação
# Garante que o Django saiba como autenticar um usuário customizado pelo campo correto (email)
AUTHENTICATION_BACKENDS = [
    # 🚨 CORREÇÃO: Adiciona o backend customizado para login por email
    'accounts.backends.EmailBackend', 
    'django.contrib.auth.backends.ModelBackend',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# settings.py

# Apenas para desenvolvimento (NUNCA em produção, onde você usaria apenas CORS_ALLOWED_ORIGINS)
CORS_ALLOW_ALL_ORIGINS = False 

# Domínios EXATOS permitidos (onde seu React está rodando)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173", # Porta padrão do Vite/React
    "http://127.0.0.1:5173",
    # Se você estiver usando o React/Next.js em outra porta, adicione aqui
]

# Permite que cookies de autenticação, cabeçalhos e tokens sejam incluídos em requisições CORS
CORS_ALLOW_CREDENTIALS = True


ROOT_URLCONF = 'vagali_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'vagali_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # O método mais seguro e padrão para APIs Mobile/SPA
        'rest_framework.authentication.TokenAuthentication', 
        
        # Manter a autenticação de Sessão para a "Browsable API" (a tela do navegador)
        'rest_framework.authentication.SessionAuthentication',
    ],
    # Para garantir que endpoints como o UserProfileViewSet exijam um token
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],

    # 🚨 NOVO: Configurar filtros globais
    'DEFAULT_FILTER_BACKENDS': (
        'rest_framework.filters.SearchFilter', # Adiciona a funcionalidade de busca
    ),

    
}