# Generated by Django 5.2.8 on 2025-11-12 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_palavras_chave'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='profile',
            name='descricao_servicos',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição Detalhada dos Serviços'),
        ),
        migrations.AddField(
            model_name='profile',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado (UF)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='servico_principal',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Serviço Principal'),
        ),
    ]
