# Generated by Django 5.2.8 on 2025-11-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_servicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(default='🛠️', max_length=50, verbose_name='Ícone (Emoji ou CSS class)'),
        ),
    ]
